all: install

install:
	mkdir -p /opt/AllowBRFw
	cp -r bin /opt/AllowBRFw
	cp -r etc /opt/AllowBRFw
	cp -r lib /opt/AllowBRFw
	cp -r var /opt/AllowBRFw
	chmod +x /opt/AllowBRFw/bin/AllowBRFw.sh

clean:
	rm -rf /opt/AllowBRFw
